### ISSUE TITLE
Does not handle TD rowspan

### ISSUE THREAD

**Issue by enricoros** [Addvilz/wikitable_to_csv#1]
For tables that have cells that span multiple rows, the output will be wrong. The 'shape' of the CSV will look like everything is collapsed to the left, so rows have a different amount of cells.

Ideally, the content should be duplicated in all rows, and rows should have the same amount of cells.

**Comment by Addvilz** [comment]
From my own use cases, I saw very few/no numeric wiki tables that actually have multi-row/column cells. That being said, this is probably an issue anyway, and colspan/rowspan should result in "empty cells". 

As for the same amount of cells in all rows, although RFC 4180 recommends having same number of cells in all rows, I am pretty certain all office programs, including web based ones, have full support for variable length rows in CSV. 

I'll see what I can do about this, but this little side project is low priority for me personally, if you want to submit a pull to fix this, it would be appreciated.
